### PR TITLE
Features

### PR DESCRIPTION
**Pull request by leolpaz**
On this project, I made a clone of the Newsweek page using bootstrap. My own CSS was kept to a minimum and I tried to use the maximum amount of classes possible while also trying to solve most of my problems with bootstrap.

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Hi @leolpaz :clap: :clap:
#### You have done a good job. The page looks great. However, there is a minor requirement you need to fix before this project can be approved :point_down:

#### Subscribe section:
 - One image is used in this project for the two images that stack over each other. Fix this, use two images and style, and position them like the original.

### Optional:
 - Style the subscribe button on the navbar and make it look like the original.

#### _Reviewed by Temitayo Adeleke_

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUESTED ♻

### Hey, nice project so far. I noticed that you guys are missing some key features of this project, so we have to improve a few things before moving on:

- [ ] As the previous TSE required: One image is used in this project for the two images that stack over each other. Fix this, use two images and style, and position them like the original.
But know I can't see the images: 
image



## As always, I wish you all the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Comment by leolpaz** [comment]
It seems that I asked for the review before Githack updated, my mistake, it's working now.

**Comment by kevincappuccino** [comment]
Well done @leolpaz please submit for another review, so someone can take a look at it!

**Review by kevcap — APPROVED** [review]
# [STATUS] PROJECT APPROVED 🍾

### I really like your project! Congrats @leolpaz, you did an excellent job, you have my approval to go ahead and merge this pull request!


## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Pull request merged**
